### ISSUE TITLE
cc_build.rake uses db:migrate instead of db:schema:load

### ISSUE THREAD

**Issue by greggersh** [thoughtworks/cruisecontrol.rb#65]
db:migrate should only be used by developers, it is not meant to be used as a means to load a database.  db:schema:load should be used instead.  Perhaps also db:seed to seed data.

**Comment by greggersh** [comment]
It's very well established that db:schema:load is the way to go and that you should check in your schema.rb file.  Right now, db:migrate breaks for me because a model that was used in a migration has been removed, which is completely legitimate, as opposed to not checking in your schema, which is just sloppy.  I say support and encourage the correct behavior, rather than account for deviations from the accepted standard.  But whatever works.

**Comment by thewoolleyman** [comment]
reposting prior recomment as myself ;) 

"db:schema:load will break if you don't check in schema.rb (which not everyone does). Maybe db:schema:load, with a fallback to migrate if schema.rb doesn't exist?"

**Comment by thewoolleyman** [comment]
I would say that it is just sloppy to use your app's ActiveRecord Model classes in your migrations, which may go away, as you pointed out.  If you must use an ActiveRecord model, declare a new minimal one in-line in the migration, so that the migration will never break even if you delete the table's corresponding model class from your app.

But I digress.  I think the point is we should support both approaches...

**Comment by greggersh** [comment]
Touche. ;)

**Comment by tamaloa** [comment]
+1 on db:schema:load

**Comment by bguthrie** [comment]
The right thing to do if you need to use an ActiveRecord::Base model in your migrations is to re-declare it locally. If the code is checked in and part of your app then it should run; if it doesn't run, it should be fixed or compressed and removed. This is technical debt. If your migrations don't run anymore, then what are they still doing in your db/migrate folder?

I don't want to switch it over unilaterally since that will affect a lot of other people's builds. If anyone would like to submit a patch to make migrate/schema:load configurable I think that would be nice. If not, I'll place it in the backlog as a feature.

**Comment by bguthrie** [comment]
The idea of trying to do the right thing based on the presence of schema.rb sounds good to me, but if you've been using db:migrate and don't check it in then won't you already have (an incorrect) one locally?
